### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices!

### ISSUE THREAD

**Issue by BillyMassey** [bigchina430/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by bigchina430** [comment]
Thanks for noticing that!  I added the <meta name="viewport" content="width=device-width, initial-scale=1"> tag to the head section in application.html.erb.  It looks a lot better.  I have pushed it to production

**Comment by BillyMassey** [comment]
Great Job!
